#pragma once

#include "types.h"

#define INFO_LOG_LENGTH 512
#define SHADER_SOURCE_LENGTH 1024

#define MAX_BUFFERED_RECTS 200
#define MAX_BUFFERED_TEXT 500
#define MAX_BUFFERED_DOTS 250

#define BITMAP_HEIGHT 1024
#define BITMAP_WIDTH  BITMAP_HEIGHT
#define FIRST_CHAR 32
#define CHARS_SIZE 96 

#define DEBUG_FONT_SIZE_VH 2.0